# Archivo: /TuProyecto/Config/config_preproceso.yml

io:
  input_directory: "data/input"
  #input_filename: "Tablas_de_entrada.xlsx"
  output_filename: "PreProcesamiento.xlsx" # Nombre del resultado final
  sheets_to_omit:
    - "Table of Contents"


# NUEVO: Seccion para controlar el comportamiento del script
settings:
  # Cambiar a 'true' para guardar los archivos Excel intermedios (Debug_P1, P2, P3, P4)
  # en la raiz del proyecto. Dejar en 'false' para una ejecucion mas rapida.
  debug_mode: false